[package]
name = "ime"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
slint = { workspace = true, features = ["raw-window-handle-06"] }

[target.'cfg(windows)'.dependencies]
raw-window-handle = "0.6.2"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_Ime",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
slint-build.workspace = true
